name: CI
on:
 push:
  branches:
 pull_request: 
 workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: Dev
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Lets try this way now,
          echo lets see how it goes.
          echo it is running on $ENVIRONMENT
          echo the application name is ${{APP_NAME}}
          echo the repo name is ${{github.repository}}
